name: Make macOS Machine

on: 
  workflow_dispatch:
  push:

jobs:
  macos:
    runs-on: macos-13
    steps:
      - name: Copy the files
        run: |
          git clone https://github.com/KyeEscobar1573-d/Docker-VNC

          curl -O https://pagekite.net/pk/pagekite.py
          cp Docker-VNC/.pagekite.rc ~
          sed -i'' -e 's*KITENAMEPK*${{ secrets.KITENAME }}*g' ~/.pagekite.rc
          sed -i'' -e 's*KITESECRETPK*${{ secrets.KITESECRET }}*g' ~/.pagekite.rc

          git clone https://github.com/dockur/windows.git
          wget -O loop.sh https://github.com/KyeEscobar1573-d/Docker-VNC/raw/main/loop.sh
      - name: Set everything up
        run: |
          python3.11 pagekite.py &

          sudo dscl . -create /Users/running
          sudo dscl . -create /Users/running UserShell /bin/zsh
          sudo dscl . -create /Users/running RealName "Running Be Like"
          sudo dscl . -create /Users/running UniqueID 1001
          sudo dscl . -create /Users/running PrimaryGroupID 80
          sudo dscl . -create /Users/running NFSHomeDirectory /Users/running
          sudo dscl . -passwd /Users/running "@Password123456"
          sudo dscl . -passwd /Users/running "@Password123456"
          sudo createhomedir -c -u running > /dev/null
          sudo dscl . -append /Groups/admin GroupMembership running

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 

          echo 123456 | perl -we 'BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"}; $_ = <>; chomp; s/^(.{8}).*/$1/; @p = unpack "C*", $_; foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }; print "\n"' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

          sh loop.sh
