name: Make Machine

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'win11'
        type: string
      username:
        description: 'Username'
        required: false
        default: 'actionsrunner'
        type: string
      password:
        description: 'Password (can also be set in secrets (WINDOWS_PASSWORD))'
        required: false
        default: ''
        type: string
      runNext:
        description: 'Should run next'
        required: true
        default: false
        type: boolean

  # this is no longer needed since we have the automated by me one
  # schedule:
  #   - cron: "50 */5 * * *"

# Actually it is alright to not have this
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: true
 
permissions: write-all

jobs:
  custom:
    runs-on: ubuntu-22.04
    steps:
      - name: Installs stuff
        run: |
          sudo apt update -y
          sudo apt install git wget docker-compose mosh -y
          curl -fsSL https://tailscale.com/install.sh | sh

          echo "$(whoami):password1!" | sudo chpasswd
          
          sudo tailscale up --hostname="$(if ${{ inputs.runNext }}; then echo windows; else echo manual-windows-$(TZ=Asia/Tokyo date +%H-%M-%S); fi)" --advertise-exit-node --ssh --authkey ${{ secrets.TAILSCALE_KEY }}

          sed -i 's/unset .*//g' $HOME/.bashrc
          sed -i 's/#force_color_prompt/force_color_prompt/g' $HOME/.bashrc

          echo 'source $HOME/.bashrc' | sudo tee -a /etc/profile
      - name: Copy the files
        run: |
          git clone https://github.com/dockur/windows.git .
          rm compose.yml
          wget wget https://raw.githubusercontent.com/CeciliaKelley33Mm/global/refs/heads/master/loop.sh
          chmod +x loop.sh
      - name: Set everything up
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -O docker-compose.yml https://github.com/CeciliaKelley33Mm/Docker-VNC/raw/main/custom_compose.yml

          mkdir oem

          wget -O oem/install.bat https://github.com/CeciliaKelley33Mm/Docker-VNC/raw/main/oem/install.bat

          sed -i 's/CUSTOMVERSIONPLACEHOLDER/${{ inputs.version || 'win11' }}/g' docker-compose.yml
          sed -i 's/USERNAMEPLACEHOLDER/${{ inputs.username || 'actionsrunner' }}/g' docker-compose.yml
          sed -i 's/PASSWORDPLACEHOLDER/${{ secrets.WINDOWS_PASSWORD || inputs.password || '' }}/g' docker-compose.yml

          sleep 2
          docker-compose up -d

          echo "$GH_TOKEN" > ~/gh_token.txt

          bash loop.sh ${{ inputs.runNext }} ${{ secrets.GITHUB_TOKEN }} Docker-VNC makewindows.yml main windows ${{ secrets.WEBHOOK_URL }}
